version: '3.5'

services:
  app:
    build: .
    container_name: pyworkshop-filters-app
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - .:/app
    tty: true
    depends_on:
      - elasticsearch
    command: >
      bash -c "python ./bin/wait-for-elasticsearch.py
      && python ./bin/load-data.py
      && gunicorn pyworkshop_filters.wsgi --bind 0.0.0.0:80 --workers 2 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile=-"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
    container_name: pyworkshop-filters-elasticsearch
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml

volumes:
  esdata:
    driver: local
